### ISSUE TITLE
create documentation on debugging when a test fails

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-test-runner#12]
There needs to be some (more?) documentation on what to do when a test fails. At least it needs to be clear where an error message will be.

**Comment by FritzHeiden** [comment]
I added a section to the dpctf-deploys [`README.md`](https://github.com/cta-wave/dpctf-deploy#debugging-tests)

**Comment by louaybassbouss** [comment]
@jpiesing  is the new section for Debugging in the README ok for you?

**Comment by jpiesing** [comment]
> @jpiesing is the new section for Debugging in the README ok for you?

I had a few editorial comments. I was thinking of trying to make my 1st pull request :)

**Comment by louaybassbouss** [comment]
> > @jpiesing is the new section for Debugging in the README ok for you?
> 
> I had a few editorial comments. I was thinking of trying to make my 1st pull request :)

Thanks @jpiesing that would be great :)

**Comment by jpiesing** [comment]
Pull request approved so closing.
