### ISSUE TITLE
Enable CORS Header for DPCTF Content HTTP requests

### ISSUE THREAD

**Issue by louaybassbouss** [cta-wave/dpctf-test-runner#14]
This allows us to play local content e.g. with dash.js player (make sure to access dash.js via http and not https)

**Comment by louaybassbouss** [comment]
@jpiesing CORS is now enabled please check and close this issue if it works for you. PS: You need to create a new docker image with `--reload-runner`.

**Comment by jpiesing** [comment]
Works for me. Thanks.
