### ISSUE TITLE
running the OF more than once for the same test run?

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-test-runner#19]
What happens if I run the OF more than once for the same test run?
Are the results of the later runs discarded? Do they replace the earlier runs?

**Comment by yanj-github** [comment]
Only one set of the result kept in the result file.
When OF get runs multiple times always the latest one being kept in the result. 
The later run replaces the exsisting results if there is any.

**Comment by jpiesing** [comment]
OK. Understood. This will be clearer once https://github.com/cta-wave/dpctf-test-runner/issues/20 is addressed.
