### ISSUE TITLE
results do not contain any date/time

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-test-runner#20]
The report doesn't include any date/time of when 1) the test was run (although this is on the index page) and 2) when the OF was run. I think both are needed if someone wants to send a set of results to someone else, e.g. a device implementer to a service provider or platform operator.

![image](https://user-images.githubusercontent.com/8490792/134703003-8f0f5bd0-64e2-4ded-bc8f-6284d7229ac2.png)
![image](https://user-images.githubusercontent.com/8490792/134703045-4f52e2be-9879-4f04-be5d-e9d607c1f4c3.png)

**Comment by louaybassbouss** [comment]
@jpiesing as mentioned in  https://github.com/cta-wave/dpctf-test-runner/issues/21#issuecomment-999586383 , the report includes now start/end times of the test run. Other OF parameters/config will be displayed in the HTML report as well.

**Comment by gitwjr** [comment]
Fixed. Closed.
