### ISSUE TITLE
strange behaviour with multiple file systems

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-test-runner#22]
I have to use a separate USB disc to hold the streams for this project. That disc is automatically mounted under /media/jon/<disk-id>.
Something in the system is creating files under that path but instead of creating files on the separate USB disc, they're being created under that path but on the root disc.
When I come back later, the disc is mounted under a modified path - with '1' appended on the end of the disk id - presumably because the correct path already exists and isn't empty - because of the files wrongly created under that path on the root disc.

**Comment by gitwjr** [comment]
@jpiesing to check using new install to see if its still an issue.

**Comment by gitwjr** [comment]
If there are further issues we can reopen the issue.
