### ISSUE TITLE
Delay the redirection of next.html

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-test-runner#27]
As it resolved in this issue https://github.com/cta-wave/WMAS/issues/61 
The "next.html" page for WMAS test runner next.html can be delayed by adding "&delay=3000"
e.g: https://webapitests2019.ctawave.org/wave/next.html?token=xxxxxxx&delay=3000 

I cannot do same on DPCTF test runner. 
Is there any way to add delay for the next.html page so that it can wait for the redirection please?

**Comment by louaybassbouss** [comment]
@FritzHeiden can you check this please

**Comment by FritzHeiden** [comment]
@yanj-github Do you mean `pre-test.html`? There you can set `&redirect_time=X` in seconds.

**Comment by yanj-github** [comment]
@FritzHeiden I mean "next.html" as it mentioned in here for WAMS it would be nice to have it same for dpctf as well.
https://github.com/cta-wave/WMAS/issues/61#issuecomment-1075257010

**Comment by FritzHeiden** [comment]
@yanj-github I added the delay parameter to the next.html

**Comment by yanj-github** [comment]
Thanks a lot @FritzHeiden  I will check sometime this week.
