### ISSUE TITLE
Change Name to "WAVE Streaming Media Test Suite - Devices"

### ISSUE THREAD

**Issue by gitwjr** [cta-wave/dpctf-test-runner#34]
User-visible locations in the Test Runner that reference the DPCTF Test Suite need to be updated to reflect the new name: "Wave Streaming Media Test Suite - Devices".

**Comment by jpiesing** [comment]
I can't see what has changed.

**Comment by louaybassbouss** [comment]
All HTML pages show now "WAVE Streaming Media Test Suite - Devices" instead of "DPCTF Test Runner". Can we close this issue?

**Comment by jpiesing** [comment]
> All HTML pages show now "WAVE Streaming Media Test Suite - Devices" instead of "DPCTF Test Runner". Can we close this issue?

What about the github repo README.md and so on? Do they need to be changed? They're public.

**Comment by FritzHeiden** [comment]
README.md is also updated

**Comment by gitwjr** [comment]
Closed as completed. Reopen if necessary.
