### ISSUE TITLE
host_override" not working on the latest change

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-test-runner#39]
host_override" does not working anymore on the latest main branch. It used to be working in early December. 
Can you kindly help to check if some further changes break this feature please?

**Comment by yanj-github** [comment]
Changes before this point is working fine https://github.com/cta-wave/dpctf-test-runner/commit/ddcf72da2bbd2d7f496084d21d53a6bceaa56dff

**Comment by FritzHeiden** [comment]
What value are you using for host_override?

**Comment by yanj-github** [comment]
"127.0.0.1" at the moment. 
I have used "./build.sh b1d32f5b33dc3702ed4ee3ec807ca8a7b96cd888 latest" it works fine.
But not with  "./build.sh master latest"

**Comment by FritzHeiden** [comment]
This was actually an issue with the test runner docker container. I updated the python version and now it works for me (https://github.com/cta-wave/dpctf-deploy/pull/57) Please try again

**Comment by yanj-github** [comment]
Thanks @FritzHeiden  I will check.

**Comment by yanj-github** [comment]
This is working now closing the ticket.
