### ISSUE TITLE
debug overlay on phone / tablet - "press Enter/OK to continue or Up/Down to show/hide debug overlay"

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-test-runner#5]
When running on a phone / tablet, if a test run hangs, I can scroll down to get what appears to be the beginnings of a debug menu.

![image](https://user-images.githubusercontent.com/8490792/115848603-55313c00-a424-11eb-8330-3eddfe05baca.png)

On a phone / tablet, the on-screen keyboard doesn't seem to be activated and the test runner isn't listening for touch screen input.

**Comment by FritzHeiden** [comment]
Please see https://github.com/cta-wave/dpctf-test-runner/issues/8#issuecomment-852060438

**Comment by jpiesing** [comment]
Looks good to me.
