### ISSUE TITLE
play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-test-runner#6]
When trying the tests on my Android tablet, it fails with an error;

"player.js:84 Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD"

Here's the output when monitoring via USB.

![image](https://user-images.githubusercontent.com/8490792/115850792-86ab0700-a426-11eb-80a4-d2da1c1d37d9.png)

I don't know if you can do anything in the code (even if it's just prompt the test engineer) or if this is a documentation issue.

**Comment by louaybassbouss** [comment]
yes it makes sense to mention it in the "Running Tests" section on mobile/desktop or on any platform  where autoplayback requires user gesture. each Browser has a different menu. we will check this next week.

**Comment by jpiesing** [comment]
> yes it makes sense to mention it in the "Running Tests" section on mobile/desktop or on any platform where autoplayback requires user gesture. each Browser has a different menu. we will check this next week.

I'm not convinced it's purely a documentation issue. There should be some way of recovering a test run if the test operator misses providing the user input in time.

If you can find instructions for re-enabling autoplay on recent versions of Chrome (e.g. Chrome 90) then it would be good to include that. A search with Google only finds instructions that rely on Chrome options that have been removed.

**Comment by FritzHeiden** [comment]
The play error now gets caught and added to the sessions result and report. After catching the error, the next test is executed.

**Comment by jpiesing** [comment]
OK. I can't reproduce it right now. I'll re-open it if a problem comes back.
