### ISSUE TITLE
There is no way to expand failed items for additional details on html report

### ISSUE THREAD

**Issue by afrawei** [cta-wave/dpctf-test-runner#63]
Hi,

I noticed that when clicking on report from API Results session or opening html file from downloaded results, there is a flash of additional text on failed items, but I can't expand it to read it. I have tried Chrome Version 126.0.6478.127 (Official Build) (64-bit) and MicrosoftEdge Version 126.0.2592.87 (Official build) (64-bit).

[5b691478-402d-11ef-b209-0242ac110002.zip](https://github.com/user-attachments/files/16194176/5b691478-402d-11ef-b209-0242ac110002.zip)
[video.zip](https://github.com/user-attachments/files/16194180/video.zip)

**Comment by FritzHeiden** [comment]
You can expand the details in the top header:

![image](https://github.com/user-attachments/assets/9633c7f0-4370-4819-86d4-4bb2c7651f9d)
