### ISSUE TITLE
part of video is offscreen with chrome on android due to URL bar & tabs menu

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-test-runner#7]
With Chrome on Android, part of the video is off screen due to the URL bar and tabs menu. We have tests for full screen mode - but most of them do not require full screen mode so that's not the solution. I would expect the test (or test runner?) to preferably shrink the video element so that all of it is on screen otherwise scroll the window so that all the video element is on screen.

![Screenshot_2021-04-23-11-40-42](https://user-images.githubusercontent.com/8490792/115852951-ebfff780-a428-11eb-9e61-de082fcf2da6.png)

**Comment by FritzHeiden** [comment]
Please see https://github.com/cta-wave/dpctf-test-runner/issues/8#issuecomment-852060438

**Comment by jpiesing** [comment]
Looks good to me.
