### ISSUE TITLE
test just hangs on android tablet - no console error messages

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-test-runner#8]
I'm trying the tests on my Android tablet and they (sequential track playback) repeatedly just hangs without going to completion. It's not at a consistent location.
I've used the Android USB debugger and there are no error messages on the console.
It's not a crash as the QR code drawn by the app is updated a few times after the video stalls.
It's the same version of Chrome as my phone which will run the tests. 
The tablet is several years older than the phone & hence slower. This feels therefore like a timing issue or race condition.
Please consider how users of the tests may debug problems like this. Perhaps some extra debug output on the console that can be enabled when configuring the session?

**Comment by FritzHeiden** [comment]
![image](https://user-images.githubusercontent.com/9076000/120317825-67ce4900-c2df-11eb-93c0-f0812f3a90b8.png)
![image](https://user-images.githubusercontent.com/9076000/120317844-6d2b9380-c2df-11eb-9025-3df23cb994a0.png)

Running tests works for me on mobile using firefox and brave (chromium based).

I pushed some updates that improve running tests on mobile, including proper video placement and sizing, a debug button below the video to open the info overlay, as well as catching the play() error when not interacting with the page first. Please have another look if the issue still occurs.

Any caught errors are logged into the test report, which is available on the results page (`/_wave/results.html?token=<session_token>`) after finishing all tests of a certain group.

**Comment by jpiesing** [comment]
Closing as the original problem cannot be reproduced with the current test content & the broader issue appears to be addressed by the solutions for the other issues referenced above.
