### ISSUE TITLE
UI improvements for configuring tests to run on session configuration page

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-test-runner#9]
The session configuration page UI for configuring which tests to run could be improved in several ways.

![image](https://user-images.githubusercontent.com/8490792/115868685-1fe51800-a43d-11eb-875e-63ab8d256862.png)

1) The message "select at least one API" is wrong and confusing. The test operator needs to select either one API or one test within an API. 
2) It is not remotely obvious that selecting an API name or the area to the right of the API name shows all the tests within that API.

The first comment could be addressed by changing the message to "select at least one API or at least one test within an API".
The second comment could be addressed by some kind of indication that the API name can be expanded to list the tests.

**Comment by FritzHeiden** [comment]
Modified error message and added icons as expanding indicators

**Comment by jpiesing** [comment]
OK.
